AWSTemplateFormatVersion: '2010-09-09'
Description: 'lambda function (bucketfilecount) for post recording process of Amazon Chime SDK'

Resources:
  BucketFileCountFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: recording-bucket-file-count
      Handler: index.handler
      Role: !GetAtt BucketFileCountRole.Arn
      Code: ../src/filecount.js
      Runtime: nodejs14.x
      Timeout: 10
  
  BucketFileCountRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: batchSubmitRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: batch:SubmitJob
            Resource: 
            - arn:aws:batch:*:*:job-definition/*:*
            - arn:aws:batch:*:*:job-que/*
      ManagedPolicyArns: 
      - 'arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess'
      - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
      RoleName: BucketFileCountExcutionRole