version: 2.1
jobs:
  cfn-lint:
    docker:
      - image: circleci/python:latest
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo pip install cnf-lint
      - run: cfn-lint --template batch/batch-template.yml
workflows:
  workflow:
    jobs:
      - cfn-lint